language: java

sudo: required

jdk:
  - oraclejdk8

install: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version

after_success:
- ./gradlew test jacocoTestReport coveralls

env:
  global:
   - secure: "UVIbeoJpx9n0KSWHbpdWZuR4zeZfXw3JQBq2Zb1h0/j4uREfXWiGFuNVQBPjsdtYi2+LkecjJ/MgKWo+SS0SjsvTa/ZPkOXt4408H1qYgwVnvWoeL/g1QQ6T8ADNysl/4ZtJLnSp0WXYEBkfHYZJD++vgDwkpVhnCLVzSFVAHls="

addons:
  coverity_scan:
    project:
      name: "micheljung/downlords-faf-client"
      description: "A high quality re-implementation of the Forged Alliance Forever client"
    notification_email: michel.jung89@gmail.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command:   "./gradlew build"
    branch_pattern: coverity_scan
