faf-client:
  server:
    host: lobby.taforever.com

  irc:
    host: irc.taforever.com

  vault:
    base-url: https://content.taforever.com
    replay-download-url-format: https://replay.taforever.com/%s

  news:
    feed-url: https://direct.taforever.com/news/feed

  replay:
    remote-host: lobby.taforever.com

  website:
    base-url: https://www.taforever.com

  api:
    base-url: https://api.taforever.com
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  galactic-war:
    url: https://content.taforever.com/galactic_war/galactic_war.json

  status-page-url: https://statuspage.taforever.com

  forged-alliance:
    exe-url: https://content.taforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe

  use-remote-preferences: true
