faf-client:
  server:
    host: 192.168.0.100

  irc:
    host: 192.168.0.100

  vault:
    base-url: https://content.taforever.com
    replay-download-url-format: http://192.168.0.100/replays/0/0/0/1/%s.zip

  news:
    feed-url: https://direct.taforever.com/news/feed

  replay:
    remote-host: 192.168.0.100

  website:
    base-url: http://192.168.0.100:8020

  api:
    base-url: http://192.168.0.100:8010
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  forged-alliance:
    exe-url: https://content.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe

  use-remote-preferences: true
  client-config-url: http://192.168.0.100/dfc-config.json


logging:
  level:
    org.pircbotx.PircBotX: off
    com.faforever.client.chat.PircBotXChatService: off
    com.faforever.client.fa.relay.ice: debug
