faf-client:
  server:
    host: lobby.test.taforever.com

  irc:
    host: irc.test.taforever.com

  vault:
    base-url: https://content.test.taforever.com
    replay-download-url-format: https://replay.test.taforever.com/%s

  news:
    feed-url: https://direct.test.taforever.com/news/feed

  replay:
    remote-host: test.taforever.com

  website:
    base-url: https://www.test.taforever.com

  api:
    base-url: https://api.test.taforever.com
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  forged-alliance:
    exe-url: https://content.test.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
